- name: Install required system packages for Helm and Python
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
      - python3-pip
    state: present
    update_cache: true
  become: true

- name: Add Helm signing key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    keyring: /usr/share/keyrings/helm.gpg
    state: present
  become: true

- name: Normalize architecture for APT
  ansible.builtin.set_fact:
    apt_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: Add Helm APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ apt_architecture }} signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    filename: helm-stable-debian
    state: present
  become: true

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Helm and python dependencies (kubernetes and openshift)
  ansible.builtin.apt:
    name: helm, python3-kubernetes, python3-openshift
    state: present
    update_cache: true
  become: true

- name: Download cert-manager CRDs
  ansible.builtin.get_url:
    url: https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.crds.yaml
    dest: /tmp/cert-manager.crds.yaml
  become: true

- name: Apply cert-manager CRDs
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: /tmp/cert-manager.crds.yaml
    state: present
  become: true

- name: Add Jetstack Helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
  become: true

- name: Install cert-manager via Helm
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    values:
      installCRDs: false
    state: present
  become: true
