all:
  children:
    k3s_server:
      hosts:
        server1:
          ansible_host: 192.168.1.182
    k3s_agent:
      hosts:
        agent1:
          ansible_host: 192.168.1.196
        agent2:
          ansible_host: 192.168.1.141
    proxmox:
      hosts:
        proxmox1:
          ansible_host: 192.168.1.190
          ansible_connection: local
          ansible_user: root
