- name: Install K3s server
  hosts: k3s_server
  become: yes
  roles:
    - k3s_server

- name: Wait for server token to exist
  hosts: localhost
  tasks:
    - name: Wait for k3s_node_token file
      ansible.builtin.wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        host: "{{ hostvars['server1'].ansible_host }}"
        delay: 10
        timeout: 60
        search_regex: .
      delegate_to: "{{ groups['k3s_server'][0] }}"
      become: true

- name: Refresh facts
  hosts: k3s_agent
  tasks:
    - setup:

- name: Install K3s agents
  hosts: k3s_agent
  become: yes
  roles:
    - k3s_agent

- name: Wait for K3s cluster to be ready
  hosts: k3s_server
  tasks:
    - name: Wait for K3s API server to be available
      ansible.builtin.wait_for:
        port: 6443
        delay: 10
        timeout: 60
        state: started

- name: Setup Argo CD on K3s
  hosts: k3s_server
  become: yes
  tasks:
    - name: Install cert-manager
      include_role:
        name: cert-manager

    - name: Install Argo CD
      include_role:
        name: argocd

    - name: Configure Ingress for Argo CD
      include_role:
        name: ingress

- name: Install and configure Vault (HashiCorp) on K3s
  hosts: k3s_server
  become: yes
  roles:
    - vault 
