- name: Run apt upgrade on all nodes
  import_playbook: apt_upgrade.yml

- name: Configure Kubernetes master node
  hosts: master
  become: true
  roles:
    - k8s_common
    - k8s_master

- name: Configure Kubernetes worker nodes
  hosts: workers
  become: true
  roles:
    - k8s_common
    - k8s_worker
