- name: Setup Argo CD on K3s
  hosts: k3s_server
  become: yes
  tasks:
    - name: Install cert-manager
      include_role:
        name: cert-manager

    - name: Install Argo CD
      include_role:
        name: argocd

    - name: Configure Ingress for Argo CD
      include_role:
        name: ingress
