- name: Check if node is already part of a cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_config_check

- name: Check if node is a master (API server present)
  ansible.builtin.stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: is_master_check
  when: kubelet_config_check.stat.exists
