api_user: "root@pam"
api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
node: "server-1"

template_ids: [ 1001, 1002, 1003, 1004 ]
clone_ids: [ 1101, 1102, 1103, 1104 ]
clone_names: [ "test-node1", "test-node2", "test-node3", "test-node4" ]
