- name: Include shared cluster membership check
  ansible.builtin.include_tasks: "{{ role_path }}/../k8s_common/tasks/check_cluster_status.yml"

- name: Exit if already part of a Kubernetes cluster
  ansible.builtin.meta: end_host
  when: kubelet_config_check.stat.exists

- name: Kubernetes master setup
  when: not kubelet_config_check.stat.exists
  block:
    - name: Initialize Kubernetes master
      ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Set up kube config for root
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
      changed_when: false

    - name: Install Flannel CNI plugin
      ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      changed_when: false

    - name: Include shared cluster membership check
      ansible.builtin.include_tasks: "{{ role_path }}/../k8s_common/tasks/check_cluster_status.yml"

- name: Get join command for workers
  when: is_master_check is defined and is_master_check.stat.exists
  block:
    - name: Wait for kube-apiserver to be available
      ansible.builtin.wait_for:
        port: 6443
        host: 127.0.0.1
        timeout: 60
      when: is_master_check is defined and is_master_check.stat.exists

    - name: Generate join command (only on master)
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command
      changed_when: false
      when: is_master_check is defined and is_master_check.stat.exists

    - name: Save join command for workers
      ansible.builtin.copy:
        content: "{{ join_command.stdout }}"
        dest: /tmp/k8s_join_command.sh
        mode: "0755"
      when: is_master_check is defined and is_master_check.stat.exists
